SELECT  Record_ID,
        Count_point_id,
        Direction_of_travel,
        Year,
        Count_date,
        hour,
        Region_id,
        Region_name,
        Local_authority_name,
        Road_name,
        Road_Category_ID,
        Start_junction_road_name,
        End_junction_road_name,
        Latitude,
        Longitude,
        Link_length_km,
        Pedal_cycles,
        Two_wheeled_motor_vehicles,
        Cars_and_taxis,
        Buses_and_coaches,
        LGV_Type,
        HGV_Type,
        EV_Car,
        EV_Bike,
        EV_Car+EV_Bike as Electric_Vehicles_Count,
        Electric_Vehicles_Count +Two_wheeled_motor_vehicles+Cars_and_taxis+ Buses_and_coaches+LGV_Type+HGV_Type as Motor_Vehicles_count,
        created_at,
        current_timestamp() as Transformed_Time
FROM {{ ref("bronze_traffic") }}