SELECT 'Record ID' as Record_ID,
 'Count point id'  as Count_point_id,
 'Direction of travel' as Direction_of_travel,
 'Year'  ,
 'Count date' as Count_date,
 'hour',
 'Region id' as Region_id,
 'Region name' as Region_name,
 'Local authority name' as Local_authority_name,
 'Road name' as Road_name,
 'Road Category ID' as Road_Category_ID,
 'Start junction road name' as Start_junction_road_name,
 'End junction road name' as End_junction_road_name,
 'Latitude',
 'Longitude',
 'Link length km' as Link_length_km,
 'Pedal cycles' as Pedal_cycles,
 'Two wheeled motor vehicles' as Two_wheeled_motor_vehicles,
 'Cars and taxis' as Cars_and_taxis,
 'Buses and coaches' as Buses_and_coaches,
 'LGV Type' as LGV_Type,
 'HGV Type' as HGV_Type,
 'EV Car' as EV_Car,
 'EV Bike' as EV_Bike,
 current_timestamp() as created_at
 FROM {{source("landing",'raw_traffic')}}